# Generated by Django 5.2.4 on 2025-07-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_name', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('father_occupation', models.CharField(max_length=30)),
                ('mother_occupation', models.CharField(max_length=30)),
                ('father_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media\\profile_pictures')),
            ],
        ),
    ]
