# Generated by Django 5.2.4 on 2025-07-30 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0002_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='c_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
