# Generated by Django 5.2.4 on 2025-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0003_student_c_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=10),
        ),
    ]
