# Generated by Django 5.2.4 on 2025-07-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0004_alter_student_email_alter_student_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='c_password',
        ),
    ]
