# Generated by Django 5.2.4 on 2025-08-02 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0008_alter_student_email_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
