# Generated by Django 5.2.4 on 2025-08-02 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0009_studentuser_date_joined_studentuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
