# Generated by Django 5.2.4 on 2025-08-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv_students', '0011_alter_studentuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
